### ISSUE TITLE
issue with foobar 

### ISSUE THREAD

**Issue by speedyrules** [qwertymodo/foo_input_msu#2]
hi

when putting the dll in the component folder and starting foobar i get this message:
Failed to load DLL: foo_input_msu.dll
Reason: Not a valid Win32 application.

using foobar2000 v2.0 x64

am i doing something wrong?

**Comment by qwertymodo** [comment]
64-bit foobar isn't able to load 32-bit components. I don't know when I'll have a chance to compile a 64-bit build, so the only option right now (unless you feel like building it yourself) is to run a 32-bit build of foobar.

**Comment by speedyrules** [comment]
Ok, thanks!
Tried and works fine with the 32-bit version!
